Linting Updates from 55places-Facade
neighborhoods/Facade-Inspector pull request #4
Opened 2016-10-27 14:49 UTC by zrosenbauer

- Valid-jsdoc for docblock linting
- update sort-comp to match up with component/prop preferred order

2016-10-27 14:51 UTC, zrosenbauer commented on base/rules/best-practices.js
This is up for debate. Let me know if we want to change this.

2016-10-27 16:04 UTC, cbourdage requested changes

2016-10-27 16:04 UTC, cbourdage commented on base/rules/best-practices.js
> +      },
Why are some capitalized and others not? I would suggest we just go with this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

2016-10-27 16:04 UTC, cbourdage commented on base/rules/style.js
> +    'space-before-function-paren': [2, { anonymous: 'never', named: 'never' }],
Thank you.

2016-10-28 13:52 UTC, zrosenbauer commented on base/rules/best-practices.js
> +      },
Yea I wasn't sure on this one. @jrubins what do you think makes most sense?

2016-10-28 13:53 UTC, zrosenbauer commented on base/rules/best-practices.js
> +      },
@cbourdage so everything is capitalized?

2016-10-28 14:19 UTC, zrosenbauer commented
Updated @cbourdage

2016-10-28 15:39 UTC, jrubins approved these changes

2016-10-28 15:39 UTC, jrubins commented on base/rules/best-practices.js
I mean I think we should leave this. We shouldn't encounter this often though since we prefer `const` and `let`.

2016-10-28 15:40 UTC, jrubins commented on base/rules/best-practices.js
> +      },
Yes, I like to capitalize.

2016-10-28 21:05 UTC, zrosenbauer commented on base/rules/best-practices.js
+1

2016-10-28 21:05 UTC, zrosenbauer commented
@cbourdage ping

2016-10-31 14:33 UTC, cbourdage approved these changes

2016-10-31 16:31 UTC, merged