feature/support-sass | Rearrange to support scss styles
neighborhoods/Facade-Inspector pull request #7
Opened 2016-10-31 16:43 UTC by zrosenbauer

2016-10-31 16:45 UTC, zrosenbauer commented on package.json
>    "license": "MIT",
@jrubins ;)

2016-11-01 13:07 UTC, zrosenbauer commented on package.json
>    "license": "MIT",
@jrubins ;)

2016-11-01 15:29 UTC, jrubins requested changes

2016-11-01 15:29 UTC, jrubins commented on package.json
>    "license": "MIT",
👎

2016-11-01 15:29 UTC, jrubins commented on package.json
> +  "name": "lint-config-nhds",
This is going to be a breaking change for ESLint: http://eslint.org/docs/developer-guide/shareable-configs (the package needs to be `eslint-config-{name}`. I think we should probably go with sub-packages in this repo.

2016-11-01 16:11 UTC, zrosenbauer commented on package.json
> +  "name": "lint-config-nhds",
RTFM but yea that works I'll change that up.

This does raise an issue, if we have two separate packages are we keeping them in sync as far as version? or version each one separately? I liked the idea of the github releases matching up with our package version but we could just version our entire style-guide and each subpackage seperately:

e.g.
```yaml

github-release: 1.0.0
eslint-version: 2.0.1
sass-lint-version: 1.9.0

```

2016-11-01 16:31 UTC, zrosenbauer commented
@jrubins I moved these into two separate packages. We will want to chat on how we are addressing releases.

2016-11-02 15:01 UTC, cbourdage commented on package.json
>    "license": "MIT",
LOL!

2016-11-02 15:02 UTC, cbourdage commented
Do we want to discuss this in a FED meeting?

2016-11-02 15:04 UTC, cbourdage approved these changes

2016-11-02 15:12 UTC, zrosenbauer commented
@cbourdage @jrubins yea we can chat about that then. I will stay on release 1.0.0 for now.

2016-11-02 15:38 UTC, jrubins commented
So I would say that we could model this like Babel. Where the scss "package" has its own `package.json` file and these packages are two different npm dependencies. Thoughts?

2016-11-02 16:07 UTC, zrosenbauer commented
@jrubins thats the current setup I'm planning to use...would we then release our Facade Styleguide as a whole everytime we change the packages internally? or not even use releases just version with-in each package.json file?

2016-11-03 16:45 UTC, jrubins approved these changes
A couple of small things, but otherwise looks good.

2016-11-03 16:45 UTC, jrubins commented on js/package.json
> +  "description": "Neighborhoods.com Facade Style Guide",
Revert? Since we have two packages

2016-11-03 16:45 UTC, jrubins commented on js/package.json
> +    "sass-lint": "1.9.1"
Remove

2016-11-03 16:45 UTC, jrubins commented on js/package.json
> +  "author": "Neighborhoods.com Team",
Revert? Because it's the right thing to do

2016-11-03 16:45 UTC, jrubins commented on scss/package.json
> +}
Add peer dep of sass-lint here

2016-11-03 16:48 UTC, jrubins commented
I'd say we approach versioning like Babel does it. So the first option you said.

2016-11-03 17:30 UTC, zrosenbauer commented on js/package.json
> +  "author": "Neighborhoods.com Team",
;)

2016-11-03 17:30 UTC, zrosenbauer commented on js/package.json
> +  "description": "Neighborhoods.com Facade Style Guide",
+1

2016-11-03 17:31 UTC, zrosenbauer commented on scss/package.json
> +}
+1

2016-11-03 17:35 UTC, merged